const express = require('express');
const router = express.Router();
const canalizacion = require('../canalizacion/canalizacion');
const reportePlanA = require('../reportePlanA/reportePlanA');
const reportePlanB = require('../reportePlanB/reportePlanB');
const resultExaII = require('../resultExaII/resultExaII');
const infoSeguiAccT = require('../infoSeguiAccT/infoSeguiAccT');
const planAccionTutor = require('../planAccionTutor/planAccionTutor');
const evaluacionDocen = require('../evaluacionDocen/evaluacionDocen');
const redirecc = require('../redireccionamie/redireccionamie');
const entrevistaIni = require('../entrevistaIni/entrevistaIni');
const habilitarEntrIni = require('../habilitarEntrIni/habilitarEntrIni');
const cambioT = require('../cambioT/cambioT');
//Redireccionamiento
router.get('/:num1', redirecc.Redir);
//Evaluación docente
router.post('/create', evaluacionDocen.insertEvalua);
router.get('/list/result/cali/final/:id/:grupo', evaluacionDocen.listCalifiFinal);
router.put('/activar/button/evaluaDocente', evaluacionDocen.activarButtonEvaluaDocente);
router.get('/list/Evalua/docent', evaluacionDocen.listEvaluaDocent);
router.get('/list/Group/Result/:id/:grupo', evaluacionDocen.listGroupResultIdGrupo);
router.get('/list/result/evalua/onli/one/:id', evaluacionDocen.listResultEvaluaOnliOneId);
router.get('/list/ano/All', evaluacionDocen.listAnoAll);
router.get('/list/ano/Filtrar/group/:ano', evaluacionDocen.listAnoFiltrarGroupAno);
//Entrevista inicial
router.post('/entrevistaIni', entrevistaIni.insertEntrevistaIni);
router.get('/list/verEntreIni/:id', entrevistaIni.listVerEntreIniId);
router.get('/list/verEntreIntJyPE/:idPE', entrevistaIni.listVerEntreIntJyPEIdPE);
router.get('/list/ver/ano/EntreIntJyPE/:idPE/:ano', entrevistaIni.listVerAnoEntreIntJyPEIdPEAno);
router.get('/list/ver/entrevista/inicial', entrevistaIni.listVerEntrevistaInicial);
router.get('/list/solo/grupos/inicial/:grupo', entrevistaIni.listSoloGruposInicialGrupo);
router.get('/list/one/ver/entrevista/inicial/individual/:idAlumno', entrevistaIni.listOneVerEntrevistaInicialIndividualIdAlumno);
router.get('/list/ano/All/entrevista/inicial', entrevistaIni.listAnoAllEntrevistaInicial);
router.get('/list/ano/goups/entrevista/inicial/:ano', entrevistaIni.listAnoGoupsEntrevistaInicialAno);
//Canalizaciones
router.get('/list/alumnos/All/canaliza/:id', canalizacion.listAlumnCanali);
router.post('/insert/Alumn/Canal', canalizacion.insertCanalizacion);
router.get('/list/canalizacion/:id', canalizacion.listAllCanaliza);
router.get('/list/canali/onli/one/:id', canalizacion.listIndiCana);
router.get('/list/Update/canali/one/:id', canalizacion.listUpdateCanaliza);
router.put('/update/Canalizacion/one/All/:id', canalizacion.updateCanaliza);
router.get('/list/Canaliz/no/plan/one/All/:id', canalizacion.listAlumnNoPlanDos);
router.post('/delete/canalizacion', canalizacion.deleteCanalizacion);
router.get('/list/emil/password/docente/:numControlD', canalizacion.listEmailPass);
router.get('/list/datos/alumno/for/email/:idAlumno', canalizacion.listDatosAlumFroEmail);
router.put('/update/cana/cambi/area/:id', canalizacion.updateCanalizaCaArea);
router.get('/list/canalizacion/list/All/:id', canalizacion.listCanalizacionListAllId);
router.get('/ubdate/canalizacion/:id', canalizacion.ubdateCanalizacionId);
//Reporte de plan de acción tutorial A
router.get('/list/reporte/rlan/evidencias/:id', reportePlanA.listEvidencias);
router.get('/list/reporte/Observaciones/all/:id', reportePlanA.listObservaciones);
router.post('/insert/Reporte/plan/All', reportePlanA.insertReportePlan);
router.get('/list/reporte/plan/accion/All/:id', reportePlanA.listAllReport);
router.get('/list/update/report/plan/All/accion/:id', reportePlanA.listUpdateReport);
router.put('/update/report/plan/acc/:id', reportePlanA.updateReporteplan);
router.post('/delete/report/accion/all', reportePlanA.deleteReport);
router.get('/ubdate/reportePlan/:id', reportePlanA.ubdateReportePlanId);
router.put('/updatePlan/updatereportePlan/:id', reportePlanA.updatePlanUpdateReportePlanId);
router.get('/list/reportePlan/:id', reportePlanA.listReportePlanId);
router.post('/add/reportePlan', reportePlanA.addReportePlan);
//Reporte de plan de acción tutorial B
router.get('/list/report/plan/accion/B/:id', reportePlanB.listReportPlaB);
router.get('/list/report/planB/Total/prog/:numControlD/:idDatosAccion', reportePlanB.listTotalPrograma);
router.get('/list/total/canaliz/:numControlD/:grupoTutores', reportePlanB.listTotalCanaliz);
router.get('/list/totalHom/canali/psicoT/:numControlD/:grupoTutores', reportePlanB.listPsicologoT);
router.get('/list/totalMuj/canali/psicoTM/:numControlD/:grupoTutores', reportePlanB.listPsicologoTM);
router.get('/list/totalHombr/canali/pedagogoTH/:numControlD/:grupoTutores', reportePlanB.listPedagogoTH);
router.get('/list/totalMuje/canali/pedagogoTMu/:numControlD/:grupoTutores', reportePlanB.listPedagogoTM);
router.get('/list/totalHom/canali/becaTHomb/:numControlD/:grupoTutores', reportePlanB.listBecaTHo);
router.get('/list/totalMuj/canaliM/becaTMuje/:numControlD/:grupoTutores', reportePlanB.listBecaTMu);
router.get('/list/totalHom/canaliH/EnfermeHom/:numControlD/:grupoTutores', reportePlanB.listEnfermeriaTHo);
router.get('/list/totalMuj/canaliMu/EnfermeMuj/:numControlD/:grupoTutores', reportePlanB.listEnfermeriaTMu);
router.get('/list/totalHomb/canaliHom/IncubaHom/:numControlD/:grupoTutores', reportePlanB.listIncubadoraTHo);
router.get('/list/totalMu/canaliM/IncubaM/:numControlD/:grupoTutores', reportePlanB.listIncubadoraTMu);
router.get('/list/totalHo/canaliH/Bolsa/TrabajoH/:numControlD/:grupoTutores', reportePlanB.listBolsaTrabajoTHo);
router.get('/list/totalMu/canaliM/BolsaM/TrabajoM/:numControlD/:grupoTutores', reportePlanB.listBolsaTrabajoTMu);
router.get('/list/totalH/canaliH/AcesorH/AcadeH/:numControlD/:grupoTutores', reportePlanB.listAsesorAcademicoTH);
router.get('/list/totalM/canaliM/AcesorM/AcadeM/:numControlD/:grupoTutores', reportePlanB.listAsesorAcademicoTM);
router.get('/list/Ops/Report/Plan/Accion/:numControlD/:grupoTutores', reportePlanB.listOpsReportSegui);
router.get('/list/total/no/progra/:numControlD/:grupoTutores', reportePlanB.listTotalNoProgr);
router.get('/list/all/asunti/de/tencion/:numControlD/:grupoTutores', reportePlanB.listAllAsuAten);
//Resultados del examen II
router.get('/list/result/esamenll', resultExaII.listAlumGrups);
router.get('/list/grupos/examenll/all/:grupo', resultExaII.listGruposIdTu);
router.get('/list/result/examen/ll/:grupo', resultExaII.listResultGrups);
router.get('/list/onli/idTutor/examenII/:grupo', resultExaII.listIdTutor); 
router.put('/update/result/examenll/Alum/:idAlumno17', resultExaII.insertResultExII);
router.get('/list/examenll/:id', resultExaII.listAllForGroups);
router.get('/list/Result/For/groups', resultExaII.listResultForGroups);
router.post('/update/Result/For/groups/delete', resultExaII.deleteResultExII);
router.get('/list/encargado/PE/group/all/:grupo', resultExaII.listResforGrupPE); 
router.get('/list/res/examen/ceneval/for/jefe/:grupo', resultExaII.listResAllforGrupJ); 
router.get('/list/filtrar/res/examen/ceneval/jefe', resultExaII.listFiltrarResJ); 
router.get('/list/filtr/res/exa/cene/for/anos/jefe/:ano', resultExaII.listFiltrarResultForAnos); 
//Informe de seguimiento de acción tutorial
router.post('/insert/InfoSeguiAaccTuto/informee/All', infoSeguiAccT.insertInfoSeguiAccT);
router.get('/list/ISAT/:id', infoSeguiAccT.listISAT);
router.get('/list/Onli/verISAT/:id', infoSeguiAccT.listOnliISAT); 
router.get('/list/ubdate/ISAT/:id', infoSeguiAccT.listUpdateISAT);
router.post('/ubdate/updateISAT/Aonli', infoSeguiAccT.updateISAT);
router.get('/list/PE/all/carreras/:idPE', infoSeguiAccT.listPeAllCarreras);
router.get('/list/PE/Nom/Ape/:idPE', infoSeguiAccT.listPENomApe);
router.get('/list/Total/Psi/:Carrera', infoSeguiAccT.listTotalPsico);
router.get('/list/Tota/Peda/:Carrera', infoSeguiAccT.listTotaPedag);
router.get('/list/Tot/Becas/:Carrera', infoSeguiAccT.listTotBeca);
router.get('/list/Total/Enfermeria/:Carrera', infoSeguiAccT.listTotalEnfermeria);
router.get('/list/To/Incubadora/:Carrera', infoSeguiAccT.listToIncubadora);
router.get('/list/To/bolsa/trabjo/:Carrera', infoSeguiAccT.listToBolsaTrabajo);
router.get('/list/To/Asesoria/Academica/:Carrera', infoSeguiAccT.listToAsesoriaAcademica);
router.get('/list/To/Alum/Canaliz/:Carrera', infoSeguiAccT.listTolAlumnosCanalizados);
router.post('/delete/ISAT', infoSeguiAccT.deleteISAT);
//Plan de acción tutorial
router.get('/list/alumnos/rep/plan/all/:idTutor/:grupo', planAccionTutor.listAlumnsRepAll);
router.post('/insert/atencionIndi', planAccionTutor.insertAlumAtenIndi);
router.get('/list/atencionIndi/list/:id', planAccionTutor.listInsertAlumAte);
router.get('/list/planList/groups/:id', planAccionTutor.listPlanListGroups);
router.post('/create/new/plan', planAccionTutor.createNewPlan);
router.get('/list/listPlan/:id', planAccionTutor.listListPlan);
router.get('/list/Grupo/Ciclo/:id', planAccionTutor.listGrupoCiclo);
router.post('/delete/all/plan', planAccionTutor.deleteAllPlan);
router.post('/delete/deleteSesion', planAccionTutor.deleteDeleteSesion);
router.post('/atencionDelete/delete', planAccionTutor.atencionDeleteDelete);
router.get('/list/ubdatePlanSesio/:id', planAccionTutor.listUbdatePlanSesio);
router.put('/update/planSesioUpdate/:id', planAccionTutor.updatePlanSesioUpdate);
router.get('/list/atencionIndi/list/atenc/:id', planAccionTutor.listAtencionIndiListAtenc);
router.put('/update/atencionIndi/Update/:id', planAccionTutor.updateAtencionIndiUpdate);
router.get('/list/All/Grups/tutor/alumnos/:id', planAccionTutor.listAllGroupsTutor);
router.post('/planAccionTutorial', planAccionTutor.planAccionTutorial);
router.get('/verPlan/list/:id', planAccionTutor.verPlanListId);
router.get('/ubdate/verPlan/:ubdate', planAccionTutor.ubdateVerPlanUbdate);
router.post('/ubdate/ubdatePlan', planAccionTutor.ubdateUbdatePlan);
router.post('/delete/plan', planAccionTutor.deletePlan);
router.post('/insert/sesionGrupal', planAccionTutor.insertSesionGrupal);
router.get('/list/listVerPlan/ver/:id', planAccionTutor.listListVerPlanVerId);
router.get('/plan/update/updatePlan/:id', planAccionTutor.planUpdateUpdatePlanId);
router.put('/update/updatePlan/:id', planAccionTutor.updateUpdatePlanId);
//Habilitar buttons
router.get('/verifica/button/abilitate/:id', habilitarEntrIni.verificaButtonAbilitate);
router.get('/verifica/button/abilitate/evaluaDocente/:id', habilitarEntrIni.verificaButtonAbilitateEvaluaDocente);
router.put('/activar/button/entrevistaIni/:id', habilitarEntrIni.activarButtonEntrevistaIniId);
//Cambio de tutor
router.get('/list/tutores', cambioT.listTutores);
router.put('/cambio/tutor', cambioT.cambioTutor);

module.exports = router;